global:
  imageRegistry: docker.io

networkPolicies:
  enabled: false
  type: 'k3s'

image:
  pullPolicy: IfNotPresent
  longhorn:
    manager:
      tag: v1.11.0-hotfix-1
    instanceManager:
      tag: v1.11.0-hotfix-2

service:
  ui:
    type: ClusterIP
  manager:
    type: ClusterIP

persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  volumeBindingMode: Immediate

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  replicaReplenishmentWaitInterval: 300
  disableRevisionCounter: '{"v1":"true"}'
  priorityClass: longhorn-critical

longhornManager:
  priorityClass: longhorn-critical
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

longhornDriver:
  priorityClass: longhorn-critical

longhornUI:
  replicas: 0
  priorityClass: longhorn-critical

metrics:
  serviceMonitor:
    enabled: true

preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: false