name: Deploy Alloy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: maxmorhardt/k8s
      release_name: alloy
      namespace: monitoring
      values_file: alloy/values.yaml
      helm_repo_name: grafana
      helm_repo_url: https://grafana.github.io/helm-charts
      chart: grafana/alloy
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG }}
