name: Longhorn CD

on:
  workflow_dispatch:

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: ${{ github.repository }}
      release_name: longhorn
      namespace: monitoring
      values_file: longhorn/values.yaml
      helm_repo_name: longhorn
      helm_repo_url: https://charts.longhorn.io
      chart: longhorn/longhorn
    secrets: inherit
