name: Prometheus CD

on:
  workflow_dispatch:

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: ${{ github.repository }}
      release_name: prometheus
      namespace: monitoring
      values_file: prometheus/values.yaml
      helm_repo_name: prometheus-community
      helm_repo_url: https://prometheus-community.github.io/helm-charts
      chart: prometheus-community/prometheus
    secrets: inherit
