name: Redis CD

on:
  workflow_dispatch:

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: ${{ github.repository }}
      release_name: redis
      namespace: redis
      values_file: redis/values.yaml
      helm_repo_name: bitnami
      helm_repo_url: https://charts.bitnami.com/bitnami
      chart: bitnami/redis
    secrets: inherit
