name: Zitadel CD

on:
  workflow_dispatch:

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: ${{ github.repository }}
      release_name: zitadel
      namespace: zitadel
      values_file: zitadel/values.yaml
      helm_repo_name: zitadel
      helm_repo_url: https://charts.zitadel.com
      chart: zitadel/zitadel
    secrets: inherit
